"""add branding themes table

Revision ID: 837a8dca8f90
Revises: ce0afe1427b8
Create Date: 2026-03-24 07:45:07.475600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837a8dca8f90'
down_revision = 'ce0afe1427b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_name', sa.String(length=120), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('app_tagline', sa.String(length=255), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=False),
    sa.Column('favicon_path', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('secondary_color', sa.String(length=20), nullable=False),
    sa.Column('accent_color', sa.String(length=20), nullable=False),
    sa.Column('sidebar_style', sa.String(length=50), nullable=False),
    sa.Column('navbar_style', sa.String(length=50), nullable=False),
    sa.Column('login_title', sa.String(length=255), nullable=False),
    sa.Column('login_subtitle', sa.String(length=500), nullable=False),
    sa.Column('public_hero_title', sa.String(length=255), nullable=False),
    sa.Column('public_hero_subtitle', sa.String(length=1000), nullable=False),
    sa.Column('footer_text', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branding_themes')
    # ### end Alembic commands ###
